name: Reset Board Daily

on:
  schedule:
    - cron: '0 15 * * *'  # UTC 기준 매일 자정 = 한국시간 오전 00시

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reset_draw.py
        run: |
          python reset_draw.py
